services:
  - type: web
    name: rahim-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: APP_URL
        sync: false
