services:
  - type: web
    name: rahim-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
